### ISSUE TITLE
Support for latest version of Redmine

### ISSUE THREAD

**Issue by ghost** [makotokw/redmine_render_markdown_in_repository#1]
Plase add support for latest version of Redmine ... 

Markdown not rendering in repository root  

<pre>
# Tested OS

| NO | Status| Platform|
|----|-------|---------|
|1|[![](https://cdn.rawgit.com/Neilpang/acmetest/master/status/ubuntu-latest.svg)](https://github.com/Neilpang/letest#here-are-the-latest-status)| Ubuntu
|2|[![](https://cdn.rawgit.com/Neilpang/acmetest/master/status/debian-latest.svg)](https://github.com/Neilpang/letest#here-are-the-latest-status)| Debian
|3|[![](https://cdn.rawgit.com/Neilpang/acmetest/master/status/centos-latest.svg)](https://github.com/Neilpang/letest#here-are-the-latest-status)|CentOS
</pre>

Screenshots here 

![repo_page](https://cloud.githubusercontent.com/assets/10342482/23246018/29946f96-f9aa-11e6-9135-3e9c78d5c73f.png)
![repo_view_page](https://cloud.githubusercontent.com/assets/10342482/23246017/29944db8-f9aa-11e6-8fa1-69006a0ef56c.png)

**Comment by makotokw** [comment]
Sorry for my late.

I updated this plugin to v1.1 and tested with Redmine 3.4 and 4.0.
If you have problem please let me know which Redmine version.
